export const LOGIN_ALREADY_IN_USE = 'LOGIN_ALREADY_IN_USE';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
